version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libibverbs-dev libmemcached-dev
      - run: sudo pip install --upgrade conan
      - run: ./build.sh

