version: 2
jobs:
  build:
    docker:
      - image: kristianmitk/dory:latest
    steps:
      - checkout
      - run: ./build.py clean && ./build.py -c gcc all
      - run: ./build.py clean && ./build.py -c clang all
      - run: ./build.py clean && ./build.py -c gcc -b debug all
      - run: ./build.py clean && ./build.py -c clang -b debug all
