version: 2
jobs:
  build:
    docker:
      - image: kristianmitk/dory:latest
    steps:
      - checkout
      - run: ./build.py -c gcc clean && ./build.py -c gcc all
      - run: ./build.py -c clang clean && ./build.py -c clang all
